stages:
  process_bikes_day:
    cmd: python -m prepare_bikes_day
    deps:
      - prepare_bikes_day.py
      - data/day.csv
    outs:
      - data/day_prepared.csv

  exercise_1_train:
    cmd: python -m exercise_1_train
    deps:
      - exercise_1_train.py
      - data/day_prepared.csv
    outs:
      - models/exercise_1_rf.pkl
