stages:
  process_bikes_day:
    cmd: python src/prepare_bikes_day.py
    deps:
      - src/prepare_bikes_day.py
      - data/day.csv
    outs:
      - data/day_prepared.csv

  exercise_1_train:
    cmd: python src/exercise_1_train.py
    deps:
      - src/exercise_1_train.py
      - data/day_prepared.csv
    outs:
      - models/exercise_1_rf.pkl

  exercise_1_plots:
    cmd: python src/exercise_1_plots.py
    deps:
      - src/exercise_1_plots.py
      - models/exercise_1_rf.pkl
      - data/day_prepared.csv
    plots:
      - plots/exercise_1/pdp_density_plot.png
      - plots/exercise_1/pdp_plot.png

  exercise_2_train:
    cmd: RScript src/exercise_2_train.R
    deps: 
      - src/exercise_2_train.R
      - data/day_prepared.csv
    outs: 
      - models/RandomForest_temp_hum.rds

  exercise_2_plots:
    cmd: RScript src/exercise_2_plots.R
    deps: 
      - data/day_prepared.csv
      - models/RandomForest_temp_hum.rds
      - src/exercise_2_plots.R
    outs: 
      - plots/exercise_2/pdp.png

  exercise_3_train:
    cmd: RScript src/exercise_3_train.R
    deps:
      - src/exercise_3_train.R
      - data/kc_house_data.csv
    outs:
      - models/house_model.rds

  exercise_3_plots:
    cmd: RScript src/exercise_3_plots.R
    deps:
      - src/exercise_3_plots.R
      - data/kc_house_data.csv
      - models/house_model.rds
    plots:
      - plots/exercise_3/plot.png
